package Model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="commande")
public class Commande {
	@Basic
	@Column(length=19)
	private Date date;

	@Basic
	private String etat;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="id_fournisseur")
	private Fournisseur fournisseur;

	@Basic
	@Column(name="fournisseur")
	private String fournisseur2;

	@Id
	@Column(name="id_commande")
	private long idCommande;

	@Basic
	@Column(name="prix_total_cmd")
	private Long prixTotalCmd;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="id_produit")
	private Produit produit;

	@Basic
	@Column(name="produit")
	private String produit2;

	@Basic
	@Column(name="qte_recue")
	private Long qteRecue;

	@Basic
	@Column(name="qte_restante")
	private Long qteRestante;

	@Basic
	private Long quantite;


	public Commande() {
	}

	public Commande(long idCommande) {
		this.idCommande = idCommande;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Fournisseur getFournisseur() {
		return fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public String getFournisseur2() {
		return fournisseur2;
	}

	public void setFournisseur2(String fournisseur2) {
		this.fournisseur2 = fournisseur2;
	}

	public long getIdCommande() {
		return idCommande;
	}

	public void setIdCommande(long idCommande) {
		this.idCommande = idCommande;
	}

	public Long getPrixTotalCmd() {
		return prixTotalCmd;
	}

	public void setPrixTotalCmd(Long prixTotalCmd) {
		this.prixTotalCmd = prixTotalCmd;
	}

	public Produit getProduit() {
		return produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public String getProduit2() {
		return produit2;
	}

	public void setProduit2(String produit2) {
		this.produit2 = produit2;
	}

	public Long getQteRecue() {
		return qteRecue;
	}

	public void setQteRecue(Long qteRecue) {
		this.qteRecue = qteRecue;
	}

	public Long getQteRestante() {
		return qteRestante;
	}

	public void setQteRestante(Long qteRestante) {
		this.qteRestante = qteRestante;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}