package Model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="lot")
public class Lot {
	@Basic
	@Column(name="date_entre", length=19)
	private Date dateEntre;

	@Basic
	@Column(name="dure_de_vie")
	private Long dureDeVie;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="id_fournisseur")
	private Fournisseur fournisseur;

	@Basic
	@Column(name="fournisseur_ID")
	private Long fournisseurID;

	@Id
	@Column(name="id_lot")
	private long idLot;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="id_produit")
	private Produit produit;

	@Basic
	@Column(name="produit_ID")
	private Long produitID;

	@Basic
	private Long quantite;


	public Lot() {
	}

	public Lot(long idLot) {
		this.idLot = idLot;
	}

	public Date getDateEntre() {
		return dateEntre;
	}

	public void setDateEntre(Date dateEntre) {
		this.dateEntre = dateEntre;
	}

	public Long getDureDeVie() {
		return dureDeVie;
	}

	public void setDureDeVie(Long dureDeVie) {
		this.dureDeVie = dureDeVie;
	}

	public Fournisseur getFournisseur() {
		return fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public Long getFournisseurID() {
		return fournisseurID;
	}

	public void setFournisseurID(Long fournisseurID) {
		this.fournisseurID = fournisseurID;
	}

	public long getIdLot() {
		return idLot;
	}

	public void setIdLot(long idLot) {
		this.idLot = idLot;
	}

	public Produit getProduit() {
		return produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Long getProduitID() {
		return produitID;
	}

	public void setProduitID(Long produitID) {
		this.produitID = produitID;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}