package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class CommandeDTODTODTODTO {
	private Date date;

	private String etat;

	private Fournisseur fournisseur;

	private String fournisseur2;

	private long idCommandeDTODTODTODTO;

	private Long prixTotalCmd;

	private Produit produit;

	private String produit2;

	private Long qteRecue;

	private Long qteRestante;

	private Long quantite;


	public CommandeDTODTODTODTO() {
	}

	public CommandeDTODTODTODTO(long idCommandeDTODTODTODTO) {
		this.idCommandeDTODTODTODTO = idCommandeDTODTODTODTO;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Fournisseur getFournisseur() {
		return fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public String getFournisseur2() {
		return fournisseur2;
	}

	public void setFournisseur2(String fournisseur2) {
		this.fournisseur2 = fournisseur2;
	}

	public long getIdCommandeDTODTODTODTO() {
		return idCommandeDTODTODTODTO;
	}

	public void setIdCommandeDTODTODTODTO(long idCommandeDTODTODTODTO) {
		this.idCommandeDTODTODTODTO = idCommandeDTODTODTODTO;
	}

	public Long getPrixTotalCmd() {
		return prixTotalCmd;
	}

	public void setPrixTotalCmd(Long prixTotalCmd) {
		this.prixTotalCmd = prixTotalCmd;
	}

	public Produit getProduit() {
		return produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public String getProduit2() {
		return produit2;
	}

	public void setProduit2(String produit2) {
		this.produit2 = produit2;
	}

	public Long getQteRecue() {
		return qteRecue;
	}

	public void setQteRecue(Long qteRecue) {
		this.qteRecue = qteRecue;
	}

	public Long getQteRestante() {
		return qteRestante;
	}

	public void setQteRestante(Long qteRestante) {
		this.qteRestante = qteRestante;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}
