package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class DevisDTO {
	private Date date;

	private Long idCommande;

	private long idDevisDTO;

	private Long idProduit;

	private Long prixTotalDevisDTO;

	private Long quantite;


	public DevisDTO() {
	}

	public DevisDTO(long idDevisDTO) {
		this.idDevisDTO = idDevisDTO;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Long getIdCommande() {
		return idCommande;
	}

	public void setIdCommande(Long idCommande) {
		this.idCommande = idCommande;
	}

	public long getIdDevisDTO() {
		return idDevisDTO;
	}

	public void setIdDevisDTO(long idDevisDTO) {
		this.idDevisDTO = idDevisDTO;
	}

	public Long getIdProduit() {
		return idProduit;
	}

	public void setIdProduit(Long idProduit) {
		this.idProduit = idProduit;
	}

	public Long getPrixTotalDevisDTO() {
		return prixTotalDevisDTO;
	}

	public void setPrixTotalDevisDTO(Long prixTotalDevisDTO) {
		this.prixTotalDevisDTO = prixTotalDevisDTO;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}
