package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class DevisDTODTODTODTO {
	private Date date;

	private Long idCommande;

	private long idDevisDTODTODTODTO;

	private Long idProduit;

	private Long prixTotalDevisDTODTODTODTO;

	private Long quantite;


	public DevisDTODTODTODTO() {
	}

	public DevisDTODTODTODTO(long idDevisDTODTODTODTO) {
		this.idDevisDTODTODTODTO = idDevisDTODTODTODTO;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Long getIdCommande() {
		return idCommande;
	}

	public void setIdCommande(Long idCommande) {
		this.idCommande = idCommande;
	}

	public long getIdDevisDTODTODTODTO() {
		return idDevisDTODTODTODTO;
	}

	public void setIdDevisDTODTODTODTO(long idDevisDTODTODTODTO) {
		this.idDevisDTODTODTODTO = idDevisDTODTODTODTO;
	}

	public Long getIdProduit() {
		return idProduit;
	}

	public void setIdProduit(Long idProduit) {
		this.idProduit = idProduit;
	}

	public Long getPrixTotalDevisDTODTODTODTO() {
		return prixTotalDevisDTODTODTODTO;
	}

	public void setPrixTotalDevisDTODTODTODTO(Long prixTotalDevisDTODTODTODTO) {
		this.prixTotalDevisDTODTODTODTO = prixTotalDevisDTODTODTODTO;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}
