package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class FactureDTODTODTODTO {
	private Date date;

	private String etat;

	private Long fournisseur;

	private long idFactureDTODTODTODTO;

	private Long prixTotalTtc;

	private Long produit;

	private Long quantite;


	public FactureDTODTODTODTO() {
	}

	public FactureDTODTODTODTO(long idFactureDTODTODTODTO) {
		this.idFactureDTODTODTODTO = idFactureDTODTODTODTO;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Long getFournisseur() {
		return fournisseur;
	}

	public void setFournisseur(Long fournisseur) {
		this.fournisseur = fournisseur;
	}

	public long getIdFactureDTODTODTODTO() {
		return idFactureDTODTODTODTO;
	}

	public void setIdFactureDTODTODTODTO(long idFactureDTODTODTODTO) {
		this.idFactureDTODTODTODTO = idFactureDTODTODTODTO;
	}

	public Long getPrixTotalTtc() {
		return prixTotalTtc;
	}

	public void setPrixTotalTtc(Long prixTotalTtc) {
		this.prixTotalTtc = prixTotalTtc;
	}

	public Long getProduit() {
		return produit;
	}

	public void setProduit(Long produit) {
		this.produit = produit;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}
