package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class FournisseurDTO {
	private String adresseFournisseurDTO;

	private Set<Commande> commandes = new HashSet<Commande>();

	private String emailFournisseurDTO;

	private long indFournissuer;

	private Set<Lot> lots = new HashSet<Lot>();

	private String nomFournissuer;

	private String pays;

	private String stattue;

	private String statu;

	private Long telFournisseurDTO;


	public FournisseurDTO() {
	}

	public FournisseurDTO(long indFournissuer) {
		this.indFournissuer = indFournissuer;
	}

	public String getAdresseFournisseurDTO() {
		return adresseFournisseurDTO;
	}

	public void setAdresseFournisseurDTO(String adresseFournisseurDTO) {
		this.adresseFournisseurDTO = adresseFournisseurDTO;
	}

	public Set<Commande> getCommandes() {
		return commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

	public String getEmailFournisseurDTO() {
		return emailFournisseurDTO;
	}

	public void setEmailFournisseurDTO(String emailFournisseurDTO) {
		this.emailFournisseurDTO = emailFournisseurDTO;
	}

	public long getIndFournissuer() {
		return indFournissuer;
	}

	public void setIndFournissuer(long indFournissuer) {
		this.indFournissuer = indFournissuer;
	}

	public Set<Lot> getLots() {
		return lots;
	}

	public void setLots(Set<Lot> lots) {
		this.lots = lots;
	}

	public String getNomFournissuer() {
		return nomFournissuer;
	}

	public void setNomFournissuer(String nomFournissuer) {
		this.nomFournissuer = nomFournissuer;
	}

	public String getPays() {
		return pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public String getStattue() {
		return stattue;
	}

	public void setStattue(String stattue) {
		this.stattue = stattue;
	}

	public String getStatu() {
		return statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	public Long getTelFournisseurDTO() {
		return telFournisseurDTO;
	}

	public void setTelFournisseurDTO(Long telFournisseurDTO) {
		this.telFournisseurDTO = telFournisseurDTO;
	}
}
