package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class FournisseurDTODTODTODTO {
	private String adresseFournisseurDTODTODTODTO;

	private Set<Commande> commandes = new HashSet<Commande>();

	private String emailFournisseurDTODTODTODTO;

	private long indFournissuer;

	private Set<Lot> lots = new HashSet<Lot>();

	private String nomFournissuer;

	private String pays;

	private String stattue;

	private String statu;

	private Long telFournisseurDTODTODTODTO;


	public FournisseurDTODTODTODTO() {
	}

	public FournisseurDTODTODTODTO(long indFournissuer) {
		this.indFournissuer = indFournissuer;
	}

	public String getAdresseFournisseurDTODTODTODTO() {
		return adresseFournisseurDTODTODTODTO;
	}

	public void setAdresseFournisseurDTODTODTODTO(String adresseFournisseurDTODTODTODTO) {
		this.adresseFournisseurDTODTODTODTO = adresseFournisseurDTODTODTODTO;
	}

	public Set<Commande> getCommandes() {
		return commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

	public String getEmailFournisseurDTODTODTODTO() {
		return emailFournisseurDTODTODTODTO;
	}

	public void setEmailFournisseurDTODTODTODTO(String emailFournisseurDTODTODTODTO) {
		this.emailFournisseurDTODTODTODTO = emailFournisseurDTODTODTODTO;
	}

	public long getIndFournissuer() {
		return indFournissuer;
	}

	public void setIndFournissuer(long indFournissuer) {
		this.indFournissuer = indFournissuer;
	}

	public Set<Lot> getLots() {
		return lots;
	}

	public void setLots(Set<Lot> lots) {
		this.lots = lots;
	}

	public String getNomFournissuer() {
		return nomFournissuer;
	}

	public void setNomFournissuer(String nomFournissuer) {
		this.nomFournissuer = nomFournissuer;
	}

	public String getPays() {
		return pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public String getStattue() {
		return stattue;
	}

	public void setStattue(String stattue) {
		this.stattue = stattue;
	}

	public String getStatu() {
		return statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	public Long getTelFournisseurDTODTODTODTO() {
		return telFournisseurDTODTODTODTO;
	}

	public void setTelFournisseurDTODTODTODTO(Long telFournisseurDTODTODTODTO) {
		this.telFournisseurDTODTODTODTO = telFournisseurDTODTODTODTO;
	}
}
