package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class LotDTODTODTODTO {
	private Date dateEntre;

	private Long dureDeVie;

	private Fournisseur fournisseur;

	private Long fournisseurID;

	private long idLotDTODTODTODTO;

	private Produit produit;

	private Long produitID;

	private Long quantite;


	public LotDTODTODTODTO() {
	}

	public LotDTODTODTODTO(long idLotDTODTODTODTO) {
		this.idLotDTODTODTODTO = idLotDTODTODTODTO;
	}

	public Date getDateEntre() {
		return dateEntre;
	}

	public void setDateEntre(Date dateEntre) {
		this.dateEntre = dateEntre;
	}

	public Long getDureDeVie() {
		return dureDeVie;
	}

	public void setDureDeVie(Long dureDeVie) {
		this.dureDeVie = dureDeVie;
	}

	public Fournisseur getFournisseur() {
		return fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public Long getFournisseurID() {
		return fournisseurID;
	}

	public void setFournisseurID(Long fournisseurID) {
		this.fournisseurID = fournisseurID;
	}

	public long getIdLotDTODTODTODTO() {
		return idLotDTODTODTODTO;
	}

	public void setIdLotDTODTODTODTO(long idLotDTODTODTODTO) {
		this.idLotDTODTODTODTO = idLotDTODTODTODTO;
	}

	public Produit getProduit() {
		return produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	public Long getProduitID() {
		return produitID;
	}

	public void setProduitID(Long produitID) {
		this.produitID = produitID;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}
