package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class RegistreDTO {
	private Date dateEntre;

	private Date dateSortie;

	private long idRegistreDTO;

	private String nomUser;


	public RegistreDTO() {
	}

	public RegistreDTO(long idRegistreDTO) {
		this.idRegistreDTO = idRegistreDTO;
	}

	public Date getDateEntre() {
		return dateEntre;
	}

	public void setDateEntre(Date dateEntre) {
		this.dateEntre = dateEntre;
	}

	public Date getDateSortie() {
		return dateSortie;
	}

	public void setDateSortie(Date dateSortie) {
		this.dateSortie = dateSortie;
	}

	public long getIdRegistreDTO() {
		return idRegistreDTO;
	}

	public void setIdRegistreDTO(long idRegistreDTO) {
		this.idRegistreDTO = idRegistreDTO;
	}

	public String getNomUser() {
		return nomUser;
	}

	public void setNomUser(String nomUser) {
		this.nomUser = nomUser;
	}
}
