package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class RegistreDTODTODTODTO {
	private Date dateEntre;

	private Date dateSortie;

	private long idRegistreDTODTODTODTO;

	private String nomUser;


	public RegistreDTODTODTODTO() {
	}

	public RegistreDTODTODTODTO(long idRegistreDTODTODTODTO) {
		this.idRegistreDTODTODTODTO = idRegistreDTODTODTODTO;
	}

	public Date getDateEntre() {
		return dateEntre;
	}

	public void setDateEntre(Date dateEntre) {
		this.dateEntre = dateEntre;
	}

	public Date getDateSortie() {
		return dateSortie;
	}

	public void setDateSortie(Date dateSortie) {
		this.dateSortie = dateSortie;
	}

	public long getIdRegistreDTODTODTODTO() {
		return idRegistreDTODTODTODTO;
	}

	public void setIdRegistreDTODTODTODTO(long idRegistreDTODTODTODTO) {
		this.idRegistreDTODTODTODTO = idRegistreDTODTODTODTO;
	}

	public String getNomUser() {
		return nomUser;
	}

	public void setNomUser(String nomUser) {
		this.nomUser = nomUser;
	}
}
