package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class VenteDTODTODTODTO {
	private Date dateVenteDTODTODTODTO;

	private String etat;

	private Long idClient;

	private Long idProduit;

	private long idVenteDTODTODTODTO;

	private Long quantiteVenteDTODTODTODTO;

	private Long totalVenteDTODTODTODTO;


	public VenteDTODTODTODTO() {
	}

	public VenteDTODTODTODTO(long idVenteDTODTODTODTO) {
		this.idVenteDTODTODTODTO = idVenteDTODTODTODTO;
	}

	public Date getDateVenteDTODTODTODTO() {
		return dateVenteDTODTODTODTO;
	}

	public void setDateVenteDTODTODTODTO(Date dateVenteDTODTODTODTO) {
		this.dateVenteDTODTODTODTO = dateVenteDTODTODTODTO;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Long getIdClient() {
		return idClient;
	}

	public void setIdClient(Long idClient) {
		this.idClient = idClient;
	}

	public Long getIdProduit() {
		return idProduit;
	}

	public void setIdProduit(Long idProduit) {
		this.idProduit = idProduit;
	}

	public long getIdVenteDTODTODTODTO() {
		return idVenteDTODTODTODTO;
	}

	public void setIdVenteDTODTODTODTO(long idVenteDTODTODTODTO) {
		this.idVenteDTODTODTODTO = idVenteDTODTODTODTO;
	}

	public Long getQuantiteVenteDTODTODTODTO() {
		return quantiteVenteDTODTODTODTO;
	}

	public void setQuantiteVenteDTODTODTODTO(Long quantiteVenteDTODTODTODTO) {
		this.quantiteVenteDTODTODTODTO = quantiteVenteDTODTODTODTO;
	}

	public Long getTotalVenteDTODTODTODTO() {
		return totalVenteDTODTODTODTO;
	}

	public void setTotalVenteDTODTODTODTO(Long totalVenteDTODTODTODTO) {
		this.totalVenteDTODTODTODTO = totalVenteDTODTODTODTO;
	}
}
