package DTO;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class VenteDTO {
	private Date dateVenteDTO;

	private String etat;

	private Long idClient;

	private Long idProduit;

	private long idVenteDTO;

	private Long quantiteVenteDTO;

	private Long totalVenteDTO;


	public VenteDTO() {
	}

	public VenteDTO(long idVenteDTO) {
		this.idVenteDTO = idVenteDTO;
	}

	public Date getDateVenteDTO() {
		return dateVenteDTO;
	}

	public void setDateVenteDTO(Date dateVenteDTO) {
		this.dateVenteDTO = dateVenteDTO;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Long getIdClient() {
		return idClient;
	}

	public void setIdClient(Long idClient) {
		this.idClient = idClient;
	}

	public Long getIdProduit() {
		return idProduit;
	}

	public void setIdProduit(Long idProduit) {
		this.idProduit = idProduit;
	}

	public long getIdVenteDTO() {
		return idVenteDTO;
	}

	public void setIdVenteDTO(long idVenteDTO) {
		this.idVenteDTO = idVenteDTO;
	}

	public Long getQuantiteVenteDTO() {
		return quantiteVenteDTO;
	}

	public void setQuantiteVenteDTO(Long quantiteVenteDTO) {
		this.quantiteVenteDTO = quantiteVenteDTO;
	}

	public Long getTotalVenteDTO() {
		return totalVenteDTO;
	}

	public void setTotalVenteDTO(Long totalVenteDTO) {
		this.totalVenteDTO = totalVenteDTO;
	}
}
