package com.org.server.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="bon_réception")
public class BonRéception {
	@Basic
	private Long commande;

	@Basic
	private Date date;

	@Id
	@Column(name="id_bon")
	private long idBon;

	@Basic
	@Column(name="quantite_livr")
	private Long quantiteLivr;


	public BonRéception() {
	}

	public BonRéception(long idBon) {
		this.idBon = idBon;
	}

	public Long getCommande() {
		return commande;
	}

	public void setCommande(Long commande) {
		this.commande = commande;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public long getIdBon() {
		return idBon;
	}

	public void setIdBon(long idBon) {
		this.idBon = idBon;
	}

	public Long getQuantiteLivr() {
		return quantiteLivr;
	}

	public void setQuantiteLivr(Long quantiteLivr) {
		this.quantiteLivr = quantiteLivr;
	}
}