package com.org.server.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="categorie")
public class Categorie {
	@Id
	@Column(name="id_cat")
	private long idCat;

	@Basic
	@Column(name="Nom_cat")
	private String nomCat;

	@OneToMany(targetEntity=com.org.server.model.Produit.class, mappedBy="categorie", cascade=CascadeType.MERGE)
	private Set<Produit> produits = new HashSet<Produit>();

	@Basic
	private Long total;


	public Categorie() {
	}

	public Categorie(long idCat) {
		this.idCat = idCat;
	}

	public long getIdCat() {
		return idCat;
	}

	public void setIdCat(long idCat) {
		this.idCat = idCat;
	}

	public String getNomCat() {
		return nomCat;
	}

	public void setNomCat(String nomCat) {
		this.nomCat = nomCat;
	}

	public Set<Produit> getProduits() {
		return produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}

	public Long getTotal() {
		return total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}
}