package com.org.server.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="fournisseur")
public class Fournisseur {
	@Basic
	@Column(name="adresse_fournisseur")
	private String adresseFournisseur;

	@OneToMany(targetEntity=com.org.server.model.Commande.class, mappedBy="fournisseur", cascade=CascadeType.MERGE)
	private Set<Commande> commandes = new HashSet<Commande>();

	@Basic
	@Column(name="email_fournisseur")
	private String emailFournisseur;

	@Id
	@Column(name="ind_fournissuer")
	private long indFournissuer;

	@OneToMany(targetEntity=com.org.server.model.Lot.class, mappedBy="fournisseur", cascade=CascadeType.MERGE)
	private Set<Lot> lots = new HashSet<Lot>();

	@Basic
	@Column(name="nom_fournissuer")
	private String nomFournissuer;

	@Basic
	private String pays;

	@Basic
	private String stattue;

	@Basic
	private String statu;

	@Basic
	@Column(name="tel_fournisseur")
	private Long telFournisseur;


	public Fournisseur() {
	}

	public Fournisseur(long indFournissuer) {
		this.indFournissuer = indFournissuer;
	}

	public String getAdresseFournisseur() {
		return adresseFournisseur;
	}

	public void setAdresseFournisseur(String adresseFournisseur) {
		this.adresseFournisseur = adresseFournisseur;
	}

	public Set<Commande> getCommandes() {
		return commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

	public String getEmailFournisseur() {
		return emailFournisseur;
	}

	public void setEmailFournisseur(String emailFournisseur) {
		this.emailFournisseur = emailFournisseur;
	}

	public long getIndFournissuer() {
		return indFournissuer;
	}

	public void setIndFournissuer(long indFournissuer) {
		this.indFournissuer = indFournissuer;
	}

	public Set<Lot> getLots() {
		return lots;
	}

	public void setLots(Set<Lot> lots) {
		this.lots = lots;
	}

	public String getNomFournissuer() {
		return nomFournissuer;
	}

	public void setNomFournissuer(String nomFournissuer) {
		this.nomFournissuer = nomFournissuer;
	}

	public String getPays() {
		return pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public String getStattue() {
		return stattue;
	}

	public void setStattue(String stattue) {
		this.stattue = stattue;
	}

	public String getStatu() {
		return statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	public Long getTelFournisseur() {
		return telFournisseur;
	}

	public void setTelFournisseur(Long telFournisseur) {
		this.telFournisseur = telFournisseur;
	}
}