package com.org.server.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="vente")
public class Vente {
	@Basic
	@Column(name="date_vente")
	private Date dateVente;

	@Basic
	private String etat;

	@Basic
	@Column(name="id_client")
	private Long idClient;

	@Basic
	@Column(name="id_produit")
	private Long idProduit;

	@Id
	@Column(name="id_vente")
	private long idVente;

	@Basic
	@Column(name="quantite_vente")
	private Long quantiteVente;

	@Basic
	@Column(name="total_vente")
	private Long totalVente;


	public Vente() {
	}

	public Vente(long idVente) {
		this.idVente = idVente;
	}

	public Date getDateVente() {
		return dateVente;
	}

	public void setDateVente(Date dateVente) {
		this.dateVente = dateVente;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Long getIdClient() {
		return idClient;
	}

	public void setIdClient(Long idClient) {
		this.idClient = idClient;
	}

	public Long getIdProduit() {
		return idProduit;
	}

	public void setIdProduit(Long idProduit) {
		this.idProduit = idProduit;
	}

	public long getIdVente() {
		return idVente;
	}

	public void setIdVente(long idVente) {
		this.idVente = idVente;
	}

	public Long getQuantiteVente() {
		return quantiteVente;
	}

	public void setQuantiteVente(Long quantiteVente) {
		this.quantiteVente = quantiteVente;
	}

	public Long getTotalVente() {
		return totalVente;
	}

	public void setTotalVente(Long totalVente) {
		this.totalVente = totalVente;
	}
}