package com.org.server.dto;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class BonRéception {
	private Long commande;

	private Date date;

	private long idBon;

	private Long quantiteLivr;


	public BonRéception() {
	}

	public BonRéception(long idBon) {
		this.idBon = idBon;
	}

	public Long getCommande() {
		return commande;
	}

	public void setCommande(Long commande) {
		this.commande = commande;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public long getIdBon() {
		return idBon;
	}

	public void setIdBon(long idBon) {
		this.idBon = idBon;
	}

	public Long getQuantiteLivr() {
		return quantiteLivr;
	}

	public void setQuantiteLivr(Long quantiteLivr) {
		this.quantiteLivr = quantiteLivr;
	}
}