package com.org.server.dto;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Devis {
	private Date date;

	private Long idCommande;

	private long idDevis;

	private Long idProduit;

	private Long prixTotalDevis;

	private Long quantite;


	public Devis() {
	}

	public Devis(long idDevis) {
		this.idDevis = idDevis;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Long getIdCommande() {
		return idCommande;
	}

	public void setIdCommande(Long idCommande) {
		this.idCommande = idCommande;
	}

	public long getIdDevis() {
		return idDevis;
	}

	public void setIdDevis(long idDevis) {
		this.idDevis = idDevis;
	}

	public Long getIdProduit() {
		return idProduit;
	}

	public void setIdProduit(Long idProduit) {
		this.idProduit = idProduit;
	}

	public Long getPrixTotalDevis() {
		return prixTotalDevis;
	}

	public void setPrixTotalDevis(Long prixTotalDevis) {
		this.prixTotalDevis = prixTotalDevis;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}