package com.org.server.dto;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Facture {
	private Date date;

	private String etat;

	private Long fournisseur;

	private long idFacture;

	private Long prixTotalTtc;

	private Long produit;

	private Long quantite;


	public Facture() {
	}

	public Facture(long idFacture) {
		this.idFacture = idFacture;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getEtat() {
		return etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	public Long getFournisseur() {
		return fournisseur;
	}

	public void setFournisseur(Long fournisseur) {
		this.fournisseur = fournisseur;
	}

	public long getIdFacture() {
		return idFacture;
	}

	public void setIdFacture(long idFacture) {
		this.idFacture = idFacture;
	}

	public Long getPrixTotalTtc() {
		return prixTotalTtc;
	}

	public void setPrixTotalTtc(Long prixTotalTtc) {
		this.prixTotalTtc = prixTotalTtc;
	}

	public Long getProduit() {
		return produit;
	}

	public void setProduit(Long produit) {
		this.produit = produit;
	}

	public Long getQuantite() {
		return quantite;
	}

	public void setQuantite(Long quantite) {
		this.quantite = quantite;
	}
}