package com.org.server.dto;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Registre {
	private Date dateEntre;

	private Date dateSortie;

	private long idRegistre;

	private String nomUser;


	public Registre() {
	}

	public Registre(long idRegistre) {
		this.idRegistre = idRegistre;
	}

	public Date getDateEntre() {
		return dateEntre;
	}

	public void setDateEntre(Date dateEntre) {
		this.dateEntre = dateEntre;
	}

	public Date getDateSortie() {
		return dateSortie;
	}

	public void setDateSortie(Date dateSortie) {
		this.dateSortie = dateSortie;
	}

	public long getIdRegistre() {
		return idRegistre;
	}

	public void setIdRegistre(long idRegistre) {
		this.idRegistre = idRegistre;
	}

	public String getNomUser() {
		return nomUser;
	}

	public void setNomUser(String nomUser) {
		this.nomUser = nomUser;
	}
}